import type { EntityId } from '../common/types.js';
import type { SetType } from '../enums/set-type.js';
import type { ProgressionStrategyType } from '../enums/progression-strategy-type.js';
import type { ExerciseSet } from '../entities/exercise-set.js';

export type ProgressionSuggestionStatus = 'PENDING' | 'APPLIED' | 'EDITED' | 'IGNORED';

/**
 * Suggested target performance for a single set.
 */
export interface ProgressionSetSuggestion {
  readonly setNumber: number;
  readonly weight: number;
  readonly reps: number;
  readonly type?: SetType;
  readonly targetRpe?: number;
  readonly targetRir?: number;
}

/**
 * Deterministic suggestion generated by a ProgressionStrategy.
 * Never silently modifies user workouts; requires explicit user action:
 * Apply / Edit / Ignore.
 */
export interface ProgressionSuggestion {
  readonly id: EntityId;
  readonly exerciseId: EntityId;
  readonly strategyType: ProgressionStrategyType;
  readonly title: string;
  readonly summary: string;
  readonly evidence: string;
  readonly suggestedSets: readonly ProgressionSetSuggestion[];
  readonly status: ProgressionSuggestionStatus;
  readonly createdAt: string;
}

// Config interfaces for the 9 pluggable strategies:

export interface LinearProgressionConfig {
  readonly targetReps: number;
  readonly incrementKg: number;
}

export interface DoubleProgressionConfig {
  readonly minReps: number;
  readonly maxReps: number;
  readonly incrementKg: number;
}

export interface DynamicDoubleProgressionConfig {
  readonly minReps: number;
  readonly maxReps: number;
  readonly incrementKg: number;
}

export interface RepGoalProgressionConfig {
  readonly totalRepGoal: number;
  readonly incrementKg: number;
}

export interface PercentageProgressionConfig {
  readonly targetPercentage: number; // e.g. 0.80 for 80%
  readonly targetReps: number;
  readonly manualE1rm?: number;
}

export interface RpeRirProgressionConfig {
  readonly targetRpe?: number;
  readonly targetRir?: number;
  readonly incrementKg: number;
}

export interface TopSetBackoffProgressionConfig {
  readonly topSetReps: number;
  readonly backoffPercentage: number; // e.g. 0.90 (-10%)
  readonly backoffSets: number;
  readonly backoffReps: number;
  readonly incrementKg: number;
}

export interface CustomProgressionConfig {
  readonly stepKg: number;
  readonly repTarget: number;
  readonly description?: string;
}

export type ProgressionRuleConfig =
  | { type: ProgressionStrategyType.MANUAL }
  | { type: ProgressionStrategyType.LINEAR_PROGRESSION; config: LinearProgressionConfig }
  | { type: ProgressionStrategyType.DOUBLE_PROGRESSION; config: DoubleProgressionConfig }
  | {
      type: ProgressionStrategyType.DYNAMIC_DOUBLE_PROGRESSION;
      config: DynamicDoubleProgressionConfig;
    }
  | { type: ProgressionStrategyType.REP_GOAL; config: RepGoalProgressionConfig }
  | { type: ProgressionStrategyType.PERCENTAGE_BASED; config: PercentageProgressionConfig }
  | { type: ProgressionStrategyType.RPE_RIR_BASED; config: RpeRirProgressionConfig }
  | { type: ProgressionStrategyType.TOP_SET_BACKOFF; config: TopSetBackoffProgressionConfig }
  | { type: ProgressionStrategyType.CUSTOM; config: CustomProgressionConfig };

/**
 * Context input for evaluating progression on an exercise.
 */
export interface ProgressionContext {
  readonly exerciseId: EntityId;
  readonly exerciseName?: string;
  readonly plannedSets: readonly {
    readonly setNumber: number;
    readonly weight?: number;
    readonly reps?: number;
    readonly type?: SetType;
  }[];
  readonly previousSets: readonly ExerciseSet[];
  readonly estimated1Rm?: number;
}

/**
 * Interface implemented by every pluggable progression strategy.
 */
export interface ProgressionStrategy {
  readonly type: ProgressionStrategyType;
  evaluate(context: ProgressionContext, config?: unknown): ProgressionSuggestion | null;
}
